name: Code Review with ChatGPT

on:
  pull_request:
    branches:
      - main

jobs:
  code_review:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Get changed files
        id: changed_files
        run: |
          changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- 'src/**/*.js' 'src/**/*.ts')
          changed_files="${changed_files//$'\n'/ }"
          echo "Changed Files: $changed_files"
          echo "changed_files=$changed_files" >> $GITHUB_ENV

      - name: Add Code Review
        id: add_code_review
        run: node code_review.js ${{ github.event.pull_request.changed_files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Install jq
        run: sudo apt-get install jq

      - name: Debugging REVIEWS
        run: |
          echo 'REVIEWS:'
          echo "$REVIEWS" | jq .
        env:
          REVIEWS: ${{ steps.code_review.outputs.reviews }}
